package main

var headerTmpl = `
//Generated by https://github.com/c4milo/govsphere
//Do not modify
//Copyright (c) 2014, Cloudescape. All rights reserved.

`

var importsTmpl = `
import (
	gowsdl "github.com/c4milo/gowsdl/generator"
)
`

var moTmpl = doTmpl

var doTmpl = `
{{$comment := comment .Description}}
{{$type := makePublic .Name true}}
{{$namespace := .Namespace}}
{{if $comment}} {{$comment}} {{end}}
type {{$type}} struct {
	{{$extends := toGoType .Extends}}
	{{lookUpNamespace $extends $namespace}}
	{{range .Properties}}
		{{$fieldComment := comment .Description}}
		{{$privileges := comment .RequiredPrivileges}}
		{{$fieldType := toGoType .Type}}
		{{if $fieldComment}} {{$fieldComment}} {{end}}{{if $privileges}} {{$privileges}} {{end}}
		{{makePublic .Name true}} {{lookUpNamespace $fieldType $namespace}}
	{{end}}
}

{{range .Methods}}
{{$mcomment := comment .Description}}
{{$returnType := toGoType .ReturnValue.Type}}
{{if $mcomment}} {{$mcomment}} {{end}}
func ({{$namespace}} *{{$type}}) {{makePublic .Name true}}(
{{range .Parameters}} {{$ptype := toGoType .Type}} {{replaceReservedWords .Name}} {{lookUpNamespace $ptype $namespace}}, {{end}}
) ({{if $returnType}}{{lookUpNamespace $returnType $namespace}},{{end}} error) {
	{{if $returnType}}
		return nil, nil
	{{else}}
		return nil
	{{end}}
}
{{end}}
`

var enumTmpl = `
{{$type := .Name}}
{{$comment := comment .Description}}
{{if $comment}} {{$comment}} {{end}}
type {{$type}} string
const (
	{{range .Constants}}
		{{$constComment := comment .Description}}
		{{if $constComment}} {{$constComment}} {{end}}
		{{makePublic .Name true}}_{{$type}} {{$type}} = "{{.Name}}"
	{{end}}
)
`

var faultTmpl = doTmpl
