//Generated by https://github.com/c4milo/govsphere
//Do not modify
//Copyright (c) 2014, Cloudescape. All rights reserved.

package fault

type NoConnectedDatastore struct {
}

type OperationDisabledByGuest struct {
}

type OvfHardwareExport struct {
}

type VmFaultToleranceTooManyVMsOnHost struct {
}

type VMotionLinkDown struct {
}

type BackupBlobWriteFailure struct {
}

type WillModifyConfigCpuRequirements struct {
}

type LicenseRestricted struct {
}

type CannotDecryptPasswords struct {
}

type OvfUnsupportedAttribute struct {
}

type CannotDisableDrsOnClustersWithVApps struct {
}

type AdminDisabled struct {
}

type AdminNotDisabled struct {
}

type DeviceHotPlugNotSupported struct {
}

type DisallowedDiskModeChange struct {
}

type CannotMoveVsanEnabledHost struct {
}

type CannotPlaceWithoutPrerequisiteMoves struct {
}

type ConcurrentAccess struct {
}

type ConflictingConfiguration struct {
}

type DiskNotSupported struct {
}

type DasConfigFault struct {
}

type ConnectedIso struct {
}

type CpuIncompatible81EDX struct {
}

type CustomizationFault struct {
}

type DVPortNotSupported struct {
}

type EVCAdmissionFailedCPUFeaturesForMode struct {
}

type FaultToleranceCannotEditMem struct {
}

type DestinationSwitchFull struct {
}

type DeviceUnsupportedForVmVersion struct {
}

type EVCAdmissionFailedVmActive struct {
}

type DeviceControllerNotSupported struct {
}

type FileNotWritable struct {
}

type DisallowedChangeByService struct {
}

type FcoeFaultPnicHasNoPortSet struct {
}

type AffinityConfigured struct {
}

type DiskIsNonLocal struct {
}

type DiskIsLastRemainingNonSSD struct {
}

type DuplicateDisks struct {
}

type DiskMoveTypeNotSupported struct {
}

type AuthMinimumAdminPermission struct {
}

type AlreadyUpgraded struct {
}

type GuestComponentsOutOfDate struct {
}

type CannotAccessFile struct {
}

type DuplicateVsanNetworkInterface struct {
}

type DrsVmotionIncompatibleFault struct {
}

type EVCAdmissionFailed struct {
}

type DvsOperationBulkFault struct {
}

type CannotChangeHaSettingsForFtSecondary struct {
}

type HostConfigFailed struct {
}

type CannotAddHostWithFTVmToDifferentCluster struct {
}

type CannotAccessVmComponent struct {
}

type HostNotReachable struct {
}

type IncompatibleDefaultDevice struct {
}

type EVCAdmissionFailedCPUVendorUnknown struct {
}

type CannotPowerOffVmInCluster struct {
}

type ExtendedFault struct {
}

type FaultToleranceNotSameBuild struct {
}

type FcoeFault struct {
}

type CannotMoveVmWithNativeDeltaDisk struct {
}

type FaultToleranceAntiAffinityViolated struct {
}

type CannotDisconnectHostWithFaultToleranceVm struct {
}

type EVCAdmissionFailedHostSoftwareForMode struct {
}

type CustomizationPending struct {
}

type CollectorAddressUnset struct {
}

type ConflictingDatastoreFound struct {
}

type InvalidBmcRole struct {
}

type InsufficientStandbyCpuResource struct {
}

type CannotDeleteFile struct {
}

type InsufficientDisks struct {
}

type InvalidDrsBehaviorForFtVm struct {
}

type DrsDisabledOnVm struct {
}

type GuestAuthenticationChallenge struct {
}

type InvalidHostState struct {
}

type DvsScopeViolated struct {
}

type FileNotFound struct {
}

type DisableAdminNotSupported struct {
}

type InvalidProperty struct {
}

type InsufficientCpuResourcesFault struct {
}

type InsufficientResourcesFault struct {
}

type HostCommunication struct {
}

type EVCAdmissionFailedCPUVendor struct {
}

type EVCAdmissionFailedHostDisconnected struct {
}

type FaultToleranceVmNotDasProtected struct {
}

type CpuIncompatible1ECX struct {
}

type InaccessibleVFlashSource struct {
}

type DvsNotAuthorized struct {
}

type InvalidVmConfig struct {
}

type FaultTolerancePrimaryPowerOnNotAttempted struct {
}

type LargeRDMConversionNotSupported struct {
}

type DeviceUnsupportedForVmPlatform struct {
}

type EightHostLimitViolated struct {
}

type GenericDrsFault struct {
}

type ExpiredFeatureLicense struct {
}

type InvalidHostName struct {
}

type DiskIsUSB struct {
}

type FailToLockFaultToleranceVMs struct {
}

type GenericVmConfigFault struct {
}

type FaultToleranceNotLicensed struct {
}

type DeltaDiskFormatNotSupported struct {
}

type EVCAdmissionFailedHostSoftware struct {
}

type FtIssuesOnHost struct {
}

type FailToEnableSPBM struct {
}

type HostInDomain struct {
}

type FileLocked struct {
}

type MissingBmcSupport struct {
}

type DeviceBackingNotSupported struct {
}

type InvalidDasConfigArgument struct {
}

type InvalidArgument struct {
}

type IscsiFaultVnicHasActivePaths struct {
}

type InaccessibleDatastore struct {
}

type HostIncompatibleForFaultTolerance struct {
}

type InsufficientMemoryResourcesFault struct {
}

type IndependentDiskVMotionNotSupported struct {
}

type FileNameTooLong struct {
}

type InUseFeatureManipulationDisallowed struct {
}

type HAErrorsAtDest struct {
}

type InvalidDiskFormat struct {
}

type InvalidName struct {
}

type LicenseKeyEntityMismatch struct {
}

type InvalidAffinitySettingFault struct {
}

type HostNotConnected struct {
}

type DiskHasPartitions struct {
}

type GuestPermissionDenied struct {
}

type InsufficientPerCpuCapacity struct {
}

type InsufficientHostCpuCapacityFault struct {
}

type DuplicateName struct {
}

type FileFault struct {
}

type InvalidProfileReferenceHost struct {
}

type MemoryHotPlugNotSupported struct {
}

type InvalidDeviceOperation struct {
}

type MismatchedVMotionNetworkNames struct {
}

type NasConnectionLimitReached struct {
}

type InvalidLogin struct {
}

type MksConnectionLimitReached struct {
}

type HostAccessRestrictedToManagementServer struct {
}

type InvalidCAMServer struct {
}

type InvalidFolder struct {
}

type ImportOperationBulkFault struct {
}

type IncorrectFileType struct {
}

type IscsiFaultVnicAlreadyBound struct {
}

type InvalidIpmiLoginInfo struct {
}

type HostInventoryFull struct {
}

type IDEDiskNotSupported struct {
}

type NasConfigFault struct {
}

type InvalidType struct {
}

type ManagedObjectNotFound struct {
}

type NoActiveHostInCluster struct {
}

type ImportHostAddFailure struct {
}

type InsufficientStorageSpace struct {
}

type IscsiFaultVnicNotFound struct {
}

type InvalidNetworkResource struct {
}

type InsufficientAgentVmsDeployed struct {
}

type NoPermissionOnHost struct {
}

type MethodFault struct {
}

type InvalidLicense struct {
}

type IscsiFaultVnicNotBound struct {
}

type InvalidController struct {
}

type IscsiFaultPnicInUse struct {
}

type InvalidDatastoreState struct {
}

type InvalidCollectorVersion struct {
}

type GuestProcessNotFound struct {
}

type LicenseExpired struct {
}

type HostIncompatibleForRecordReplay struct {
}

type FullStorageVMotionNotSupported struct {
}

type IscsiFaultInvalidVnic struct {
}

type LicenseEntityNotFound struct {
}

type InvalidPrivilege struct {
}

type NotSupportedHostInCluster struct {
}

type InvalidDeviceSpec struct {
}

type NotEnoughLicenses struct {
}

type InvalidLocale struct {
}

type OvfConnectedDevice struct {
}

type OvfDuplicatedElementBoundary struct {
}

type IncorrectHostInformation struct {
}

type InvalidPowerState struct {
}

type InvalidHostConnectionState struct {
}

type NicSettingMismatch struct {
}

type LimitExceeded struct {
}

type NotEnoughLogicalCpus struct {
}

type IscsiFaultVnicIsLastPath struct {
}

type NumVirtualCpusExceedsLimit struct {
}

type InvalidSnapshotFormat struct {
}

type IscsiFaultVnicHasWrongUplink struct {
}

type LogBundlingFailed struct {
}

type OvfConsumerPowerOnFault struct {
}

type InvalidRequest struct {
}

type MissingLinuxCustResources struct {
}

type LicenseAssignmentFailed struct {
}

type IpHostnameGeneratorError struct {
}

type InvalidClientCertificate struct {
}

type MismatchedNetworkPolicies struct {
}

type OvfDiskOrderConstraint struct {
}

type MethodDisabled struct {
}

type InvalidState struct {
}

type MethodAlreadyDisabledFault struct {
}

type MismatchedBundle struct {
}

type InsufficientHostMemoryCapacityFault struct {
}

type MigrationFeatureNotSupported struct {
}

type NoGuestHeartbeat struct {
}

type NamespaceWriteProtected struct {
}

type NoCompatibleSoftAffinityHost struct {
}

type MemorySizeNotSupportedByDatastore struct {
}

type NamespaceLimitReached struct {
}

type InsufficientVFlashResourcesFault struct {
}

type InvalidResourcePoolStructureFault struct {
}

type NoHost struct {
}

type NoHostSuitableForFtSecondary struct {
}

type OvfInvalidPackage struct {
}

type MaintenanceModeFileMove struct {
}

type NoCompatibleHostWithAccessToDevice struct {
}

type MissingPowerOnConfiguration struct {
}

type AlreadyExists struct {
}

type NoPermissionOnAD struct {
}

type NotAuthenticated struct {
}

type NoCompatibleHost struct {
}

type PatchBinariesNotFound struct {
}

type NotSupportedHostForVsan struct {
}

type OvfFault struct {
}

type InvalidDeviceBacking struct {
}

type OvfMappedOsId struct {
}

type NetworkCopyFault struct {
}

type MultipleSnapshotsNotSupported struct {
}

type InvalidIpmiMacAddress struct {
}

type NetworkInaccessible struct {
}

type NetworksMayNotBeTheSame struct {
}

type NoCompatibleDatastore struct {
}

type NotADirectory struct {
}

type OvfInternalError struct {
}

type NotSupportedHost struct {
}

type MissingPowerOffConfiguration struct {
}

type IscsiFault struct {
}

type NumVirtualCoresPerSocketNotSupported struct {
}

type OvfConsumerInvalidSection struct {
}

type CAMServerRefusedConnection struct {
}

type NotSupportedHostForVFlash struct {
}

type CannotAddHostWithFTVmAsStandalone struct {
}

type InvalidFormat struct {
}

type OvfNoSupportedHardwareFamily struct {
}

type NoVmInVApp struct {
}

type NoLicenseServerConfigured struct {
}

type NotSupported struct {
}

type OvfExportFailed struct {
}

type InvalidOperationOnSecondaryVm struct {
}

type OvfProperty struct {
}

type OutOfBounds struct {
}

type NotUserConfigurableProperty struct {
}

type NonPersistentDisksNotSupported struct {
}

type NoPermission struct {
}

type CannotMoveVmWithDeltaDisk struct {
}

type OvfUnknownEntity struct {
}

type OvfAttribute struct {
}

type OvfCpuCompatibilityCheckNotSupported struct {
}

type LicenseDowngradeDisallowed struct {
}

type IscsiFaultVnicInUse struct {
}

type PatchSuperseded struct {
}

type ReplicationInvalidOptions struct {
}

type CloneFromSnapshotNotSupported struct {
}

type OvfUnsupportedElementValue struct {
}

type MissingWindowsCustResources struct {
}

type OvfElementInvalidValue struct {
}

type OvfPropertyValue struct {
}

type LinuxVolumeNotClean struct {
}

type NoCompatibleHardAffinityHost struct {
}

type PatchAlreadyInstalled struct {
}

type RawDiskNotSupported struct {
}

type CpuIncompatible struct {
}

type NoVirtualNic struct {
}

type DomainNotFound struct {
}

type OvfConstraint struct {
}

type NotEnoughCpus struct {
}

type RebootRequired struct {
}

type PatchNotApplicable struct {
}

type NoPeerHostFound struct {
}

type DatastoreNotWritableOnHost struct {
}

type OperationNotSupportedByGuest struct {
}

type ReplicationIncompatibleWithFT struct {
}

type OvfPropertyType struct {
}

type OvfInvalidVmName struct {
}

type NoGateway struct {
}

type OvfUnsupportedPackage struct {
}

type DeviceNotSupported struct {
}

type MissingNetworkIpConfig struct {
}

type OvfDuplicateElement struct {
}

type OvfConsumerValidationFault struct {
}

type NotAFile struct {
}

type MemorySnapshotOnIndependentDisk struct {
}

type OvfImport struct {
}

type DisallowedOperationOnFailoverHost struct {
}

type OvfConsumerFault struct {
}

type SharedBusControllerNotSupported struct {
}

type AlreadyConnected struct {
}

type ExpiredEditionLicense struct {
}

type NotSupportedDeviceForFT struct {
}

type MigrationNotReady struct {
}

type OvfImportFailed struct {
}

type ReadOnlyDisksWithLegacyDestination struct {
}

type OvfDiskMappingNotFound struct {
}

type BlockedByFirewall struct {
}

type OvfUnsupportedDiskProvisioning struct {
}

type OvfConsumerCommunicationError struct {
}

type NoVcManagedIpConfigured struct {
}

type SnapshotMoveFromNonHomeNotSupported struct {
}

type RollbackFailure struct {
}

type OvfNoHostNic struct {
}

type SsdDiskNotAvailable struct {
}

type QuiesceDatastoreIOForHAFailed struct {
}

type CannotMoveHostWithFaultToleranceVm struct {
}

type CannotAccessVmDisk struct {
}

type OvfUnknownDeviceBacking struct {
}

type NamespaceFull struct {
}

type OvfUnsupportedElement struct {
}

type StorageDrsIolbDisabledInternally struct {
}

type StorageDrsCannotMoveSharedDisk struct {
}

type CannotCreateFile struct {
}

type OvfUnknownDevice struct {
}

type OvfHostResourceConstraint struct {
}

type DvsFault struct {
}

type NetworkDisruptedAndConfigRolledBack struct {
}

type PatchMetadataNotFound struct {
}

type ProfileUpdateFailed struct {
}

type SnapshotLocked struct {
}

type OvfElement struct {
}

type ClockSkew struct {
}

type NonVmwareOuiMacNotSupportedHost struct {
}

type OvfExport struct {
}

type OvfInvalidValueEmpty struct {
}

type OvfUnsupportedDeviceBackingOption struct {
}

type OvfMissingHardware struct {
}

type CpuHotPlugNotSupported struct {
}

type ToolsImageNotAvailable struct {
}

type OvfCpuCompatibility struct {
}

type OvfNoSpaceOnController struct {
}

type OvfWrongNamespace struct {
}

type OvfInvalidValueReference struct {
}

type OvfUnsupportedType struct {
}

type HotSnapshotMoveNotSupported struct {
}

type DatacenterMismatch struct {
}

type PatchMissingDependencies struct {
}

type SwitchNotInUpgradeMode struct {
}

type OvfPropertyQualifierIgnored struct {
}

type EVCAdmissionFailedCPUModelForMode struct {
}

type QuestionPending struct {
}

type ExpiredAddonLicense struct {
}

type DeviceNotFound struct {
}

type DiskTooSmall struct {
}

type FaultToleranceNeedsThickDisk struct {
}

type RestrictedVersion struct {
}

type SwitchIpUnset struct {
}

type InsufficientHostCapacityFault struct {
}

type EVCAdmissionFailedCPUModel struct {
}

type OvfConsumerCallbackFault struct {
}

type RDMPointsToInaccessibleDisk struct {
}

type FileAlreadyExists struct {
}

type SecurityError struct {
}

type RDMNotSupported struct {
}

type FeatureRequirementsNotMet struct {
}

type FileTooLarge struct {
}

type GuestOperationsUnavailable struct {
}

type OvfUnableToExportDisk struct {
}

type TooManyDisksOnLegacyHost struct {
}

type OperationDisallowedOnHost struct {
}

type RemoveFailed struct {
}

type StorageDrsCannotMoveManuallyPlacedVm struct {
}

type IncompatibleSetting struct {
}

type OvfXmlFormat struct {
}

type FilesystemQuiesceFault struct {
}

type DisallowedMigrationDeviceAttached struct {
}

type OvfInvalidValueFormatMalformed struct {
}

type StorageDrsUnableToMoveFiles struct {
}

type OvfHostValueNotParsed struct {
}

type ReplicationVmFault struct {
}

type HostConnectFault struct {
}

type GuestOperationsFault struct {
}

type PowerOnFtSecondaryFailed struct {
}

type UnsupportedVimApiVersion struct {
}

type StorageDrsDatacentersCannotShareDatastore struct {
}

type ReplicationDiskConfigFault struct {
}

type OvfPropertyNetworkExport struct {
}

type SSLDisabledFault struct {
}

type InsufficientStandbyResource struct {
}

type SnapshotFault struct {
}

type VirtualHardwareCompatibilityIssue struct {
}

type DvsApplyOperationFault struct {
}

type ResourceInUse struct {
}

type SoftRuleVioCorrectionDisallowed struct {
}

type FaultToleranceCpuIncompatible struct {
}

type VmFaultToleranceInvalidFileBacking struct {
}

type HostConfigFault struct {
}

type ToolsImageCopyFailed struct {
}

type UncustomizableGuest struct {
}

type StorageDrsCannotMoveIndependentDisk struct {
}

type InvalidCAMCertificate struct {
}

type VMINotSupported struct {
}

type OvfPropertyQualifier struct {
}

type SecondaryVmAlreadyRegistered struct {
}

type PatchMetadataInvalid struct {
}

type TooManyDevices struct {
}

type InvalidDatastorePath struct {
}

type SnapshotIncompatibleDeviceInVm struct {
}

type OvfUnexpectedElement struct {
}

type VmotionInterfaceNotEnabled struct {
}

type ReplicationFault struct {
}

type InvalidEvent struct {
}

type VmValidateMaxDevice struct {
}

type UnconfiguredPropertyValue struct {
}

type SwapDatastoreUnset struct {
}

type VmToolsUpgradeFault struct {
}

type OvfUnsupportedDeviceExport struct {
}

type SecondaryVmAlreadyDisabled struct {
}

type ResourceNotAvailable struct {
}

type SoftRuleVioCorrectionImpact struct {
}

type UnsupportedGuest struct {
}

type InsufficientFailoverResourcesFault struct {
}

type VspanDestPortConflict struct {
}

type WakeOnLanNotSupportedByVmotionNIC struct {
}

type OvfWrongElement struct {
}

type StorageDrsCannotMoveManuallyPlacedSwapFile struct {
}

type SecondaryVmNotRegistered struct {
}

type HostPowerOpFailed struct {
}

type InvalidIndexArgument struct {
}

type InsufficientStandbyMemoryResource struct {
}

type StorageDrsDisabledOnVm struct {
}

type VMotionLinkCapacityLow struct {
}

type ReadHostResourcePoolTreeFailed struct {
}

type VAppPropertyFault struct {
}

type PowerOnFtSecondaryTimedout struct {
}

type InvalidBundle struct {
}

type SwapPlacementOverrideNotSupported struct {
}

type InvalidNetworkInType struct {
}

type VirtualDiskModeNotSupported struct {
}

type VspanPortConflict struct {
}

type IncompatibleHostForFtSecondary struct {
}

type ToolsAutoUpgradeNotSupported struct {
}

type OvfNetworkMappingNotSupported struct {
}

type InvalidPropertyValue struct {
}

type InvalidDatastore struct {
}

type ReplicationConfigFault struct {
}

type VmFaultToleranceConfigIssue struct {
}

type VAppNotRunning struct {
}

type VAppTaskInProgress struct {
}

type IORMNotSupportedHostOnDatastore struct {
}

type InvalidEditionLicense struct {
}

type RequestCanceled struct {
}

type UnSupportedDatastoreForVFlash struct {
}

type MultipleCertificatesVerifyFault struct {
}

type WakeOnLanNotSupported struct {
}

type VirtualHardwareVersionNotSupported struct {
}

type SuspendedRelocateNotSupported struct {
}

type SecondaryVmAlreadyEnabled struct {
}

type IscsiFaultVnicHasNoUplinks struct {
}

type VmHostAffinityRuleViolation struct {
}

type StorageDrsCannotMoveFTVm struct {
}

type ThirdPartyLicenseAssignmentFailed struct {
}

type VmFaultToleranceIssue struct {
}

type SnapshotDisabled struct {
}

type LegacyNetworkInterfaceInUse struct {
}

type RDMNotSupportedOnDatastore struct {
}

type MissingIpPool struct {
}

type StorageDrsCannotMoveVmWithNoFilesInLayout struct {
}

type VmLimitLicense struct {
}

type LicenseSourceUnavailable struct {
}

type MemorySizeNotSupported struct {
}

type VmfsMountFault struct {
}

type SnapshotCopyNotSupported struct {
}

type InvalidIpfixConfig struct {
}

type VmFaultToleranceConfigIssueWrapper struct {
}

type VAppOperationInProgress struct {
}

type NasVolumeNotMounted struct {
}

type ToolsAlreadyUpgraded struct {
}

type SnapshotNoChange struct {
}

type InvalidPropertyType struct {
}

type Timedout struct {
}

type VAppConfigFault struct {
}

type InventoryHasStandardAloneHosts struct {
}

type TooManyConcurrentNativeClones struct {
}

type StorageDrsCannotMoveDiskInMultiWriterMode struct {
}

type TooManyNativeCloneLevels struct {
}

type VMotionInterfaceIssue struct {
}

type ToolsUpgradeCancelled struct {
}

type LicenseServerUnavailable struct {
}

type IscsiFaultVnicHasMultipleUplinks struct {
}

type StorageDrsCannotMoveVmWithMountedCDROM struct {
}

type TooManySnapshotLevels struct {
}

type VirtualDiskBlocksNotFullyProvisioned struct {
}

type UnrecognizedHost struct {
}

type MemorySizeNotRecommended struct {
}

type VsanDiskFault struct {
}

type VmConfigIncompatibleForFaultTolerance struct {
}

type UserNotFound struct {
}

type SnapshotRevertIssue struct {
}

type UnsupportedDatastore struct {
}

type NotSupportedHostInHACluster struct {
}

type MigrationDisabled struct {
}

type VMotionProtocolIncompatible struct {
}

type VmfsAlreadyMounted struct {
}

type TooManyNativeClonesOnFile struct {
}

type NonHomeRDMVMotionNotSupported struct {
}

type TooManyConsecutiveOverrides struct {
}

type NoDiskSpace struct {
}

type VMOnConflictDVPort struct {
}

type VspanSameSessionPortConflict struct {
}

type UncommittedUndoableDisk struct {
}

type VspanPromiscuousPortNotSupported struct {
}

type MigrationFault struct {
}

type VsanFault struct {
}

type VmConfigIncompatibleForRecordReplay struct {
}

type NoSubjectName struct {
}

type InvalidNasCredentials struct {
}

type VirtualEthernetCardNotSupported struct {
}

type NumVirtualCpusNotSupported struct {
}

type ToolsUnavailable struct {
}

type MountError struct {
}

type NasSessionCredentialConflict struct {
}

type SwapDatastoreNotWritableOnHost struct {
}

type VramLimitLicense struct {
}

type LargeRDMNotSupportedOnDatastore struct {
}

type NonADUserRequired struct {
}

type VspanPortMoveFault struct {
}

type VMotionAcrossNetworkNotSupported struct {
}

type NoPermissionOnNasVolume struct {
}

type VMOnVirtualIntranet struct {
}

type VMotionNotSupported struct {
}

type NoAvailableIp struct {
}

type NoClientCertificate struct {
}

type NotSupportedHostInDvs struct {
}

type VmPowerOnDisabled struct {
}

type VimFault struct {
}

type WillResetSnapshotDirectory struct {
}

type OvfConsumerUndefinedPrefix struct {
}

type OvfDuplicatedPropertyIdImport struct {
}

type UnsharedSwapVMotionNotSupported struct {
}

type OvfConsumerUndeclaredSection struct {
}

type WipeDiskFault struct {
}

type MissingController struct {
}

type OvfMissingElementNormalBoundary struct {
}

type NotImplemented struct {
}

type VMotionNotLicensed struct {
}

type OvfHardwareCheck struct {
}

type VmfsAmbiguousMount struct {
}

type NotFound struct {
}

type OvfPropertyNetwork struct {
}

type OvfToXmlUnsupportedElement struct {
}

type OvfConnectedDeviceIso struct {
}

type VsanClusterUuidMismatch struct {
}

type NoDiskFound struct {
}

type OvfUnsupportedDeviceBackingInfo struct {
}

type OvfMissingElement struct {
}

type OvfPropertyExport struct {
}

type OvfUnsupportedSubType struct {
}

type NumVirtualCpusIncompatible struct {
}

type OvfInvalidValueConfiguration struct {
}

type OvfConnectedDeviceFloppy struct {
}

type OvfUnsupportedAttributeValue struct {
}

type ReplicationVmConfigFault struct {
}

type OvfDuplicatedPropertyIdExport struct {
}

type PatchIntegrityError struct {
}

type PlatformConfigFault struct {
}

type RDMNotPreserved struct {
}

type SSPIChallenge struct {
}

type PhysCompatRDMNotSupported struct {
}

type OvfInvalidValue struct {
}

type ReplicationNotSupportedOnHost struct {
}

type SnapshotCloneNotSupported struct {
}

type StorageDrsCannotMoveVmInUserFolder struct {
}

type StorageVMotionNotSupported struct {
}

type TooManyHosts struct {
}

type RDMConversionNotSupported struct {
}

type RuleViolation struct {
}

type ShrinkDiskFault struct {
}

type RuntimeFault struct {
}

type PatchInstallFailed struct {
}

type OvfUnsupportedSection struct {
}

type TooManyGuestLogons struct {
}

type UnsupportedVmxLocation struct {
}

type ToolsInstallationInProgress struct {
}

type RemoteDeviceNotSupported struct {
}

type StorageDrsCannotMoveTemplate struct {
}

type StorageVmotionIncompatible struct {
}

type VmMetadataManagerFault struct {
}

type WillLoseHAProtection struct {
}

type SystemError struct {
}

type SnapshotMoveToNonHomeNotSupported struct {
}

type RecordReplayDisabled struct {
}

type VFlashModuleNotSupported struct {
}

type UnexpectedFault struct {
}

type FileBackedPortNotSupported struct {
}

type VMotionNotConfigured struct {
}

type SnapshotMoveNotSupported struct {
}

type VmFaultToleranceOpIssuesList struct {
}

type DirectoryNotEmpty struct {
}

type VspanPortgroupTypeChangeFault struct {
}

type VspanPortgroupPromiscChangeFault struct {
}

type TaskInProgress struct {
}

type SSLVerifyFault struct {
}

type OvfMissingAttribute struct {
}

type InvalidGuestLogin struct {
}

type ToolsImageSignatureCheckFailed struct {
}

type UnusedVirtualDiskBlocksNotScrubbed struct {
}

type UnexpectedCustomizationFault struct {
}

type VmConfigFault struct {
}

type VolumeEditorError struct {
}

type PatchMetadataCorrupted struct {
}

type VmWwnConflict struct {
}

type VmAlreadyExistsInDatacenter struct {
}

type VFlashModuleVersionIncompatible struct {
}

type CannotAccessNetwork struct {
}

type OvfSystemFault struct {
}

type VmMonitorIncompatibleForFaultTolerance struct {
}

type AlreadyBeingManaged struct {
}

type NoDisksToCustomize struct {
}

type CannotReconfigureVsanWhenHaEnabled struct {
}

type CannotAccessVmConfig struct {
}

type CannotUseNetwork struct {
}

type VspanPortPromiscChangeFault struct {
}

type CannotDisableSnapshot struct {
}

type CannotModifyConfigCpuRequirements struct {
}

type AgentInstallFailed struct {
}

type AnswerFileUpdateFailed struct {
}

type DatabaseError struct {
}

type CpuCompatibilityUnknown struct {
}

type InvalidDasRestartPriorityForFtVm struct {
}

type CannotAccessLocalSource struct {
}

type CannotChangeVsanNodeUuid struct {
}

type CannotChangeDrsBehaviorForFtSecondary struct {
}

type MethodNotFound struct {
}

type CannotAddHostWithFTVmToNonHACluster struct {
}

type CannotChangeVsanClusterUuid struct {
}

type CannotMoveFaultToleranceVm struct {
}

type BackupBlobReadFailure struct {
}

type CannotAccessVmDevice struct {
}

type ApplicationQuiesceFault struct {
}

type ActiveDirectoryFault struct {
}

type OvfPropertyQualifierDuplicate struct {
}

type DestinationVsanDisabled struct {
}
